=== C0mpy/XML/src/main/resources/schema/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="www.tim7.org"
    targetNamespace="www.tim7.org" elementFormDefault="qualified">
    <xsd:element name="akt">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="preambula"/>
                <xsd:choice>
                    <xsd:sequence maxOccurs="1" minOccurs="1">
                        <xsd:element ref="deo" maxOccurs="unbounded" minOccurs="2"/>
                    </xsd:sequence>
                    <xsd:sequence maxOccurs="1" minOccurs="1">
                        <xsd:element ref="clan" maxOccurs="20" minOccurs="2"/>
                    </xsd:sequence>
                    <xsd:sequence maxOccurs="1">
                        <xsd:element ref="glava" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:choice>
            </xsd:sequence>
            <xsd:attribute name="naslov" type="xsd:string" use="required"/>
            <xsd:attribute name="status" type="status" use="required"/>
            <xsd:attribute name="drzava" type="xsd:string"/>
            <xsd:attribute name="pokrajina" type="xsd:string"/>
            <xsd:attribute name="grad" type="xsd:string"/>
            <xsd:attribute name="donosilac" type="xsd:string"/>
            <xsd:attribute name="broj" type="xsd:string"/>
            <xsd:attribute name="datum" type="xsd:string"/>
            <xsd:attribute name="gradonacelnik" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="preambula"/>
    <xsd:element name="deo">
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded" minOccurs="2">
                <xsd:element ref="glava"/>
            </xsd:sequence>
            <xsd:attribute name="broj" type="xsd:string" use="required"/>
            <xsd:attribute name="naziv">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[A-Z]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="glava">
        <xsd:complexType>
            <xsd:choice maxOccurs="1">
                <xsd:sequence maxOccurs="1" minOccurs="1">
                    <xsd:element ref="odeljak" maxOccurs="unbounded"/>
                </xsd:sequence>
                <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" ref="clan"/>
                </xsd:sequence>
                <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" ref="sadrzaj"/>
                </xsd:sequence>
            </xsd:choice>
            <xsd:attribute name="broj" use="required">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[MDCLXVI]+"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="naziv" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="odeljak">
        <xsd:complexType>
            <xsd:choice>
                <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" ref="pododeljak"/>
                </xsd:sequence>
                <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" ref="clan"/>
                </xsd:sequence>
            </xsd:choice>
            <xsd:attribute name="broj" type="xsd:int" use="required"/>
            <xsd:attribute name="naziv" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="pododeljak">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="clan"/>
            </xsd:sequence>
            <xsd:attribute name="naziv" type="xsd:string" use="required"/>
            <xsd:attribute form="unqualified" name="oznaka" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="clan">
        <xsd:complexType>
            <xsd:choice>
                <xsd:sequence maxOccurs="unbounded" minOccurs="1">
                    <xsd:element ref="stav"/>
                </xsd:sequence>
            </xsd:choice>
            <xsd:attribute name="naziv" type="xsd:string" use="optional"/>
            <xsd:attribute name="broj" type="xsd:int" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="stav">
        <xsd:complexType>
            <xsd:choice>
                <xsd:sequence maxOccurs="unbounded" minOccurs="1">
                    <xsd:element ref="tacka"/>
                </xsd:sequence>
                <xsd:element ref="sadrzaj"/>
            </xsd:choice>
            <xsd:attribute name="id" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="tacka">
        <xsd:complexType>
            <xsd:choice>
                <xsd:sequence maxOccurs="unbounded" minOccurs="2">
                    <xsd:element ref="podtacka"/>
                </xsd:sequence>
                <xsd:element ref="sadrzaj"/>
            </xsd:choice>
            <xsd:attribute name="broj" type="xsd:int"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="podtacka">
        <xsd:complexType>
            <xsd:choice>
                <xsd:sequence maxOccurs="1">
                    <xsd:element maxOccurs="unbounded" minOccurs="2" ref="alineja"/>
                </xsd:sequence>
                <xsd:element maxOccurs="1" ref="sadrzaj"/>
            </xsd:choice>
            <xsd:attribute name="broj" type="xsd:int"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="alineja">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="sadrzaj"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="sadrzaj" type="xsd:string"/>
    <xsd:simpleType name="status">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="((U NACELU)|(U PROCEDURI)|(U CELOSTI)|(USVOJEN))"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== C0mpy/XML/src/main/resources/xml/akt1_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt xmlns="www.tim7.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="www.tim7.org ../schema/akt.xsd"
    naslov="ПРАВИЛНИК О УСЛОВИМА, НАЧИНУ КОРИШЋЕЊА И ПОТРОШЊИ ГОРИВА СЛУЖБЕНИХ ВОЗИЛА СЛУЖБЕ ЗА ЗАЈЕДНИЧКЕ ПОСЛОВЕ" 
    status="USVOJEN" drzava="РЕПУБЛИКА СРБИЈА" pokrajina="АУТОНОМНА ПОКРАЈИНА ВОЈВОДИНА" grad="ГРАД НОВИ САД" 
    donosilac="ГРАДОНАЧЕЛНИК ГРАДА НОВОГ САДА" broj="031-1/2015-360-II" datum="22. децембар 2015. године" 
    gradonacelnik="Милош Вучевић, с.р.">
    
    <preambula>
        На основу члана 16. став 2. Статута Града Новог Сада
        - пречишћен текст ("Службени лист Града Новог Сада",
        број 43/08), Градоначелник Града Новог Сада доноси
    </preambula>
    <clan broj="1">
       <stav>
           <sadrzaj>
               Овим правилником уређују се услови, начин коришћења
               и потрошња горива службених возила (у даљем тексту:
               возила), према типу и техничким карактеристикама возила
               Службе за заједничке послове Града Новог Сада (у даљем
               тексту: Служба), koja се користе за потребе Скупштине
               Града Новог Сада, Градоначелника Града Новог Сада,
               Градског већа Града Новог Сада, градских управа, посеб-
               них организација и служби, (у даљем тексту: органи Града),
               начин обрачуна потрошње горива, права и обавезе запо-
               слених у вези са коришћењем горива, као и друга питања
               од значаја за потрошњу горива.
           </sadrzaj>
       </stav>
    </clan>
    <clan broj="2">
        <stav>
            <sadrzaj>
                Под горивом, у смислу овог правилника, сматрају се
                органска фосилна горива и нафтни деривати, који се кори-
                сте за погон мотора са унутрашњим сагоревањем.
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="3">
        <stav>
            <sadrzaj>
                Возила, у смислу овог правилника, су путничка и друга
                моторна возила, која су у власништву Службе.
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="4">
        <stav>
            <sadrzaj>
                Запослени овлашћени да управљају возилом, у смислу
                овог правилника, су лица која су у радном односу у Служби,
                на неодређено или одређено време, а који су решењем
                распоређени на радна места возача-професионални возач
                или друга лица запослена у органима Града, за обављање
                редовних делатности ( у даљем тексту: возач).
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="5">
        <stav>
            <sadrzaj>
                Врста и количина горива која се набавља за возила за
                потребе органа Града одређена је финансијским планом
                Службе, за сваку календарску годину.
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="6">
        <stav>
            <sadrzaj>
                Гориво се може набављати само код добављача који
                је изабран у поступку јавне набавке и коме је додељен уго-
                вор о снабдевању горивом, за текућу годину.
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="7">
        <stav>
            <sadrzaj>
                Право на точење горива има возач који има путни налог
                за управљање возилом.
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="8">
        <stav>
            <sadrzaj>
                За свако путовање, возачу се издаје путни налог за
                управљање тим возилом, у складу са прописима.
            </sadrzaj>
        </stav>
        <stav>
            <sadrzaj>
                Возач је дужан да за купљено гориво обавезно узме
                фискални рачун, који је саставни део путног налога.
            </sadrzaj>
        </stav>
    </clan>
    <clan broj="9">
        <stav>
            <sadrzaj>
                За купљено гориво у земљи, плаћање се врши искључиво
                дебитном електронском картицом, а у иностранству гото-
                вим новцем.
            </sadrzaj>
        </stav>
        <stav>
            <sadrzaj>
                Возач је дужан да фискални рачун за купљено гориво
                преда исти дан или први наредни радни дан, шефу Одсека
                аутосервиса ( у даљем тексту: шеф Одсека).
            </sadrzaj>
        </stav>
        <stav>
            <sadrzaj>
                Уколико се возач налази на службеном путовању дужан
                је да фискални рачун за купљено гориво преда истог или
                наредног дана, по повратку са службеног путовања.
            </sadrzaj>
        </stav>
    </clan>
</akt>
